package me.loghiks.hlsdownloader;

import me.loghiks.hlsdownloader.gui.GUIThread;

public class Main {

    // HIS LINE IS AUTOGENERATED, DO NOT EDIT
    public static final String APP_NAME = "HLSDownloader";

    public static void main(String[] args) throws Exception {

        if(args.length == 0) GUIThread.startThread();

    }

}
