package me.loghiks.hlsdownloader;

import me.loghiks.hlsdownloader.cli.CLI;
import me.loghiks.hlsdownloader.gui.HLSFrame;

public class Main {

    // HIS LINE IS AUTOGENERATED, DO NOT EDIT
    public static final String APP_NAME = "HLSDownloader";

    public static void main(String[] args) {

        if(args.length == 0) HLSFrame.display();
        else CLI.parseArguments(args);

    }

}
