package me.loghiks.hlsdownloader;

import me.loghiks.hlsdownloader.gui.HLSFrame;

import java.io.File;
import java.io.IOException;

public class Main {

    // HIS LINE IS AUTOGENERATED, DO NOT EDIT
    public static final String APP_NAME = "HLSDownloader";

    private static boolean CLIMode = false;

    public static void main(String[] args) {

        if(args.length == 0) {
            HLSFrame.display();
            return;
        }

        CLIMode = true;

        //TODO: CLI mode
        // Options:
        //  --url OR --file
        //  --out (file name)
        //  --error (print stacks traces in a file)

    }

    public static boolean isCLIMode() {
        return CLIMode;
    }

    public static void browseFile(File file) {

        try {
            Runtime.getRuntime().exec("explorer.exe /select," + file.getAbsolutePath());
        } catch (IOException ignored) { }

    }

}
